// AUTO-GENERATED by scripts/caelestia-theme.py - do not edit by hand.
// seed=#7d624d variant=content flavour=default mode=dark
pragma Singleton
import QtQuick
import Quickshell

Singleton {
    readonly property bool isDark: true
    readonly property string schemeVariant: "content"
    readonly property string schemeFlavour: "default"
    readonly property color mdSourceColour: "#7d624d"

    readonly property color mdBackground: "#151311"
    readonly property color mdOnBackground: "#e8e1de"
    readonly property color mdPrimary: "#e2c0a7"
    readonly property color mdOnPrimary: "#412c1a"
    readonly property color mdPrimaryContainer: "#7d624d"
    readonly property color mdOnPrimaryContainer: "#ffe1cd"
    readonly property color mdSecondary: "#d5c3b7"
    readonly property color mdOnSecondary: "#392e26"
    readonly property color mdSecondaryContainer: "#51443b"
    readonly property color mdOnSecondaryContainer: "#c4b2a6"
    readonly property color mdTertiary: "#c8c9a7"
    readonly property color mdOnTertiary: "#31321a"
    readonly property color mdTertiaryContainer: "#68694d"
    readonly property color mdOnTertiaryContainer: "#e9e9c6"
    readonly property color mdError: "#ffb4ab"
    readonly property color mdOnError: "#690005"
    readonly property color mdErrorContainer: "#93000a"
    readonly property color mdOnErrorContainer: "#ffdad6"
    readonly property color mdSurface: "#151311"
    readonly property color mdOnSurface: "#e8e1de"
    readonly property color mdSurfaceVariant: "#4f453e"
    readonly property color mdOnSurfaceVariant: "#d2c4ba"
    readonly property color mdSurfaceDim: "#151311"
    readonly property color mdSurfaceBright: "#3c3836"
    readonly property color mdSurfaceContainerLowest: "#100e0c"
    readonly property color mdSurfaceContainerLow: "#1e1b19"
    readonly property color mdSurfaceContainer: "#221f1d"
    readonly property color mdSurfaceContainerHigh: "#2d2927"
    readonly property color mdSurfaceContainerHighest: "#383432"
    readonly property color mdOutline: "#9b8e86"
    readonly property color mdOutlineVariant: "#4f453e"
    readonly property color mdShadow: "#000000"
    readonly property color mdScrim: "#000000"
    readonly property color mdInverseSurface: "#e8e1de"
    readonly property color mdInverseOnSurface: "#33302e"
    readonly property color mdInversePrimary: "#735945"

    readonly property color mdSubtleOutline: "#9b8e8633"
    readonly property color mdSubtleOutlineVariant: "#4f453e33"

    // static, non-scheme tokens
    readonly property color mdWarning: "#FFD1A9"
    readonly property color mdCharging: "#2ECC71"
}
