#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path
from types import SimpleNamespace

from PIL import Image
from materialyoucolor.hct import Hct
from materialyoucolor.utils.color_utils import argb_from_rgb

HERE = Path(__file__).resolve().parent
# Make the vendored `caelestia` package take priority over any installed copy.
sys.path.insert(0, str(HERE))

from caelestia.colourfulness import get_variant  # noqa: E402
from caelestia.material.generator import gen_scheme  # noqa: E402
from caelestia.material.score import score  # noqa: E402


# --- copied verbatim from caelestia-cli utils/wallpaper.py --------------------
def get_thumb(wall: Path, cache: Path) -> Path:
    thumb = cache / "thumbnail.jpg"

    if not thumb.exists():
        with Image.open(wall) as img:
            img = img.convert("RGB")
            img.thumbnail((128, 128), Image.Resampling.NEAREST)
            thumb.parent.mkdir(parents=True, exist_ok=True)
            img.save(thumb, "JPEG")

    return thumb


def get_smart_opts(wall: Path, cache: Path) -> dict:
    opts_cache = cache / "smart.json"

    try:
        return json.loads(opts_cache.read_text())
    except (IOError, json.JSONDecodeError):
        pass

    opts = {}

    with Image.open(get_thumb(wall, cache)) as img:
        opts["variant"] = get_variant(img)
        img.thumbnail((1, 1), Image.Resampling.LANCZOS)
        pixel = img.getpixel((0, 0))
        hct = Hct.from_int(argb_from_rgb(*pixel))
        opts["mode"] = "light" if hct.tone > 60 else "dark"

    opts_cache.parent.mkdir(parents=True, exist_ok=True)
    opts_cache.write_text(json.dumps(opts))

    return opts
# -----------------------------------------------------------------------------


# caelestia colour key -> morphism-shell ThemeService property
TOKEN_MAP = {
    "background": "mdBackground",
    "onBackground": "mdOnBackground",
    "primary": "mdPrimary",
    "onPrimary": "mdOnPrimary",
    "primaryContainer": "mdPrimaryContainer",
    "onPrimaryContainer": "mdOnPrimaryContainer",
    "secondary": "mdSecondary",
    "onSecondary": "mdOnSecondary",
    "secondaryContainer": "mdSecondaryContainer",
    "onSecondaryContainer": "mdOnSecondaryContainer",
    "tertiary": "mdTertiary",
    "onTertiary": "mdOnTertiary",
    "tertiaryContainer": "mdTertiaryContainer",
    "onTertiaryContainer": "mdOnTertiaryContainer",
    "error": "mdError",
    "onError": "mdOnError",
    "errorContainer": "mdErrorContainer",
    "onErrorContainer": "mdOnErrorContainer",
    "surface": "mdSurface",
    "onSurface": "mdOnSurface",
    "surfaceVariant": "mdSurfaceVariant",
    "onSurfaceVariant": "mdOnSurfaceVariant",
    "surfaceDim": "mdSurfaceDim",
    "surfaceBright": "mdSurfaceBright",
    "surfaceContainerLowest": "mdSurfaceContainerLowest",
    "surfaceContainerLow": "mdSurfaceContainerLow",
    "surfaceContainer": "mdSurfaceContainer",
    "surfaceContainerHigh": "mdSurfaceContainerHigh",
    "surfaceContainerHighest": "mdSurfaceContainerHighest",
    "outline": "mdOutline",
    "outlineVariant": "mdOutlineVariant",
    "shadow": "mdShadow",
    "scrim": "mdScrim",
    "inverseSurface": "mdInverseSurface",
    "inverseOnSurface": "mdInverseOnSurface",
    "inversePrimary": "mdInversePrimary",
}


def render_qml(colours: dict[str, str], mode: str, variant: str, seed_hex: str, flavour: str) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/caelestia-theme.py - do not edit by hand.",
        f"// seed=#{seed_hex} variant={variant} flavour={flavour} mode={mode}",
        "pragma Singleton",
        "import QtQuick",
        "import Quickshell",
        "",
        "Singleton {",
        f'    readonly property bool isDark: {"false" if mode == "light" else "true"}',
        f'    readonly property string schemeVariant: "{variant}"',
        f'    readonly property string schemeFlavour: "{flavour}"',
        f'    readonly property color mdSourceColour: "#{seed_hex}"',
        "",
    ]

    for key, prop in TOKEN_MAP.items():
        lines.append(f'    readonly property color {prop}: "#{colours[key]}"')

    lines += [
        "",
        f'    readonly property color mdSubtleOutline: "#{colours["outline"]}33"',
        f'    readonly property color mdSubtleOutlineVariant: "#{colours["outlineVariant"]}33"',
        "",
        "    // Static semantic colours retained for the shell.",
        '    readonly property color mdWarning: "#FFD1A9"',
        '    readonly property color mdCharging: "#2ECC71"',
        "}",
        "",
    ]

    return "\n".join(lines)


def build(wall: Path, mode: str, variant: str, flavour: str) -> tuple[dict[str, str], str, str, str]:
    """Return (colours, mode, variant, seed_hex) using caelestia's pipeline."""
    with tempfile.TemporaryDirectory() as tmp:
        cache = Path(tmp)
        thumb = get_thumb(wall, cache)

        if mode == "smart" or variant == "smart":
            smart = get_smart_opts(wall, cache)
            if mode == "smart":
                mode = smart["mode"]
            if variant == "smart":
                variant = smart["variant"]

        scheme = SimpleNamespace(name="dynamic", flavour=flavour, mode=mode, variant=variant)
        primary = score(str(thumb))
        colours = gen_scheme(scheme, primary)

    return colours, mode, variant, f"{primary.to_int() & 0xFFFFFF:06x}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("wallpaper", type=Path)
    ap.add_argument("--output", type=Path, help="write a QML singleton here")
    ap.add_argument("--variant", default="smart", help="smart | tonalspot | content | expressive | fidelity | ...")
    ap.add_argument("--mode", default="smart", choices=["smart", "dark", "light"])
    ap.add_argument("--flavour", default="default", choices=["default", "hard"])
    ap.add_argument("--json", action="store_true", help="print scheme JSON instead of writing QML")
    args = ap.parse_args()

    wall = args.wallpaper.resolve()
    if not wall.is_file():
        ap.error(f"no such wallpaper: {wall}")
    if not args.json and args.output is None:
        ap.error("--output is required unless --json is given")

    colours, mode, variant, seed_hex = build(wall, args.mode, args.variant, args.flavour)

    if args.json:
        print(json.dumps({"mode": mode, "variant": variant, "source": seed_hex, "colours": colours}))
        return 0

    assert args.output is not None
    qml = render_qml(colours, mode, variant, seed_hex, args.flavour)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    tmp = args.output.with_name(args.output.name + ".tmp")
    tmp.write_text(qml)
    os.replace(tmp, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
